// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_AirportInterfaceDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ATCDisplay;

public interface _AirportInterfaceDel extends Ice._ObjectDel
{
    java.util.List<ATCDFlight> getFlights(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    ATCDAirport getAirportInfo(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    void UpdateSimT(float inc, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    float getSimT(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getMaxFlights(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getPoints(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
