// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ATCDLandStripsHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ATCDisplay;

public final class ATCDLandStripsHolder
{
    public
    ATCDLandStripsHolder()
    {
    }

    public
    ATCDLandStripsHolder(java.util.List<ATCDLandStrip> value)
    {
        this.value = value;
    }

    public java.util.List<ATCDLandStrip> value;
}
