// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_AirportInterface_UpdateSimT.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ATCDisplay;

public abstract class Callback_AirportInterface_UpdateSimT extends Ice.OnewayCallback
{
}
